### ISSUE TITLE
we do need a notion of newline after all

### ISSUE THREAD

**Issue by mengwong** [smucclaw/sandbox#28]
an action might look like

-> pay
     to = bob, alice
     amount = 100 each

**Comment by mengwong** [comment]
proposal: in the preprocessor, add an EOL token, concretely `;`

**Comment by anka-213** [comment]
Please don't do huge squash commits with huge messages like that. It removes all sense of history, so you can't hover over a line to figure out why it was added. 

Also, the git lens plugin for VS Code tries to show the whole commit message before you can see the type on hovering, but I guess that's the plugin's fault.

**Comment by anka-213** [comment]
At least add a summary to the top, so we don't have to read the whole thing to figure out what it's about, otherwise the squashing provides zero value. Use rebase if you want to remove merge commits, and use `git rebase -i` if you want to merge tiny "fixup" commits into a single one.
